import React, { useState } from 'react';
import { Loader, Card, FormField } from '../components';

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">
          Browse through a collection of imaginative and visually stunning images generated by&nbsp;DALL‑E AI.
        </p>
      </div>

      <div className="mt-16">
        {/* search / upload / whatever your FormField does */}
        <FormField />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {/* Render cards here when you’ve fetched posts */}
            {allPosts &&
              allPosts.map((post) => <Card key={post.id} {...post} />)}
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
